# Generated by Django 3.2.5 on 2021-07-24 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PotionsCraftHelperApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='potion',
            name='image',
            field=models.ImageField(default='potions_images/default_news.jpg', upload_to='potions_images/'),
        ),
    ]
