# Generated by Django 3.2.5 on 2021-07-24 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PotionsCraftHelperApp', '0002_potion_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='potion',
            name='name',
            field=models.CharField(default='potion', max_length=100),
        ),
    ]
