# Generated by Django 3.2.5 on 2021-07-25 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PotionsCraftHelperApp', '0003_potion_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='potion',
            name='ingredients',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='potion',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
