# Generated by Django 3.2.5 on 2021-07-25 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PotionsCraftHelperApp', '0004_auto_20210725_2223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='potion',
            name='ingredients',
            field=models.CharField(max_length=1000),
        ),
    ]
