# Generated by Django 3.2.5 on 2021-08-09 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PotionsCraftHelperApp', '0007_auto_20210809_0322'),
    ]

    operations = [
        migrations.AddField(
            model_name='potion',
            name='time_up_level',
            field=models.CharField(max_length=4, null=True),
        ),
    ]
