# Generated by Django 3.2.5 on 2021-08-10 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PotionsCraftHelperApp', '0008_potion_time_up_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='potion',
            name='up_level',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='potion',
            name='up_time',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='potion',
            name='time_plus',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='potion',
            name='time_up_level',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
